version: "3"
services: 
    openface:
        build: 
            context: .
            dockerfile: Dockerfile
        image: emotional-model-1
        container_name: "emotional-model-1"
        ports:
            - "8080:8080"