version: "3"
services: 
    mongodb:
        image: "mongo:4.4.0"
        container_name: "emotional-mongo"
        environment: 
            - MONGO_INITDB_DATABASE=face-images
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=rootPass
        ports:
            - "27017-27019:27017-27019"
        volumes: 
            - ./mongo-volume:/data/db